### ISSUE TITLE
左上のロゴをトップページに戻るリンクに変更したい

### ISSUE THREAD

**Issue by junji-s** [tatsuya19881021/qin-portfolio#11]
現状のサイトでは、下層ページに遷移した後にトップページに戻る手段がない。
トップページに戻れないとUI、UX的に悪くなってしまうので、リンクにしましょう！

ロゴをリンクにするのはスタンダードだと思いますので、覚えておくといいと思います！

**Comment by tatsuya19881021** [comment]
ご指摘ありがとうございます！

いつもブラウザの戻る進むで頑張っていましたｗ

頑張ってる時点でリンク入れとけって話ですが…放置すること幾星霜。

優先的に対応致します🙇

**Comment by tatsuya19881021** [comment]
@junji-s 
プッシュ＆プルリクまで対応しました！
一旦マージまでして確認してもらう、みたいな流れのほうがやりやすいですかね？？
