### ISSUE TITLE
ブログの詳細ページのURLを変更できれば、変更したい

### ISSUE THREAD

**Issue by junji-s** [tatsuya19881021/qin-portfolio#16]
/detail/の中に詳細ページがあるのですが、SEO的にも以下の方がいいかなと思います。
/blog/各ページのID

※ただ、URLの構造は好みもあるので、変更できればしてもいいと思います！

**Comment by tatsuya19881021** [comment]
ご提案頂いた内容で変更しました！

（Figmaのコンポーネントとかそういう構成や名称を何となく合わせた形が元々の作りとしていた理由です）
