### ISSUE TITLE
時間があれば対応したい点

### ISSUE THREAD

**Issue by junji-s** [tatsuya19881021/qin-portfolio#17]
現状、デザインや見た目が元のデザインと異なる部分が多いかなと思うので、デザインに合わせたいですね！

デザインを合わせようとすると、今のコードでは実現できない点や困る点が出てくる可能性があるので、やってみてもいいかなと！
実案件だと必須になってくると思います！

**Comment by tatsuya19881021** [comment]
#22 にて対応したので、完了にします〜✨
