### ISSUE TITLE
お聞きしたいこと🙋✨

### ISSUE THREAD

**Issue by kyoichi1** [tatsuya19881021/qin-portfolio#20]
✅各componentで 下記の様にされれているのはcomponentを使うときに
　<Blog/>で呼び出せるようにされているということでしょうか？

　例:
　Blog　>　BlogSection
   　 　　>　index　内容：export { BlogSection } from "./BlogSection";

**Comment by tatsuya19881021** [comment]
@kyoichi1 
> ✅各componentで 下記の様にされれているのはcomponentを使うときに 　で呼び出せるようにされているということでしょうか？
> 
> 　例: 　Blog　>　BlogSection 　 　　>　index　内容：export { BlogSection } from "./BlogSection";

何か、不明な日本語が一部ありますが…間違った読み取りの場合は、再度コメントでご連絡お願いします。

回答としては、そうですね〜。
importする際に、例えば下記のパターンとかがスマートに書けるかもしれません。
（例で挙げてもらったのでも良かったですが、自分のやつで一部それっぽいのがあったので、それをベースに。）

`src/lib/mantine/index.ts`
```TypeScript
export { useMediaQuery } from "./useMediaQuery";
export { useViewportSize } from "./useViewportSize";
```

上記をinportする場合に…

`src/pages/index.tsx`
```TypeScript
import { useMediaQuery, useViewportSize } from "src/lib/mantine";
```

- useViewportSize は、現状使っていないので仮想な書き方ですが、そういうメリットがありそうです。

- **あ、もっとメリット的なこととしては…
例えば、Blog/index.tsx や Portfolio/index.tsx として、中に直接BlogやPortfolioコンポーネントを書いちゃうと、
idnex.tsxだらけ編集時に区別しにくくなっちゃうので、一個exportをかますことで、
編集しているファイル名とコンポーネント名が区別しやすくなるはずです！**


一応、これの参考元は下記のリポジトリとかです。（我らがKingの手法を真似ているだけですｗ）

https://github.com/lightsound/Next.js-Mantine-TailwindCSS
