### ISSUE TITLE
9/13 レビュー (おさむ)

### ISSUE THREAD

**Issue by mu0363** [tatsuya19881021/qin-portfolio#24]
全体的に綺麗なコードでとても参考になりました！ありがとうございます:bow:

1点だけ気になった箇所として粗探しみたいで恐縮なのですが:sweat:、
`BlogSection.tsx`のprops、`displayRow`が使用されていないので削除しても良いかと思います。

未使用箇所を目視で特定するのはなかなか大変なので、
`eslint-plugin-unused-imports`という便利なeslintライブラリを導入すると
簡単に不要箇所の特定や不要なimportを自動削除してくれるので一度お試しください。

自分もこれを導入してからはもう以前には戻れなくなりました :smile: 以下参考記事です！
https://chaika.hatenablog.com/entry/2022/01/17/083000

**Comment by tatsuya19881021** [comment]
@mu0363 
レビュー実施ありがとうございます😀

バレちゃいましたかｗ
一番最初にHomeと個別ページで、ダミーデータ用で表示件数を変えるようにして、
APIからのデータ時には何も対応しないまま行った名残です。

本当はどんな形でもやってあげたほうが良いかもな〜という気持ちを
この引数に現して、TODOにもしないやつです。

良いですねー、ライブラリ。
ご提案頂きありがとうございます！

ちらほらゴミが残っているかもなんで、リファクタリングで
消し去りたいと思っていますが、そちらも参考にさせて頂きます🙇
