### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by nackyAir** [tatsuya19881021/qin-portfolio#5]
### 良かったところ

Componentがスッキリとまとまっていますし、codeもスッキリまとまっていてとても良いと思いました！
Mantineを積極的に使ってらっしゃるので、とても参考になります。。。
自分のComponentが機能優先でごちゃついているので、参考にさせていただきます！
各ディレクトリにindexでexportしているのも良いと思います！

### 僭越ながら改善点です。

- Bargurを使ってMobileNavを作ると更に良くなると思います！
- Componentをパーツごとに分けると、ぱっと見たときに見やすくなるかもしれません。。。

### さいごに

初めてのレビューなのでちゃんとできているか不明ですが、
宜しくお願いいたします。

**Comment by tatsuya19881021** [comment]
@Naoki0509 
コードレビューありがとうございます！

> ### 良かったところ
> Componentがスッキリとまとまっていますし、codeもスッキリまとまっていてとても良いと思いました！ Mantineを積極的に使ってらっしゃるので、とても参考になります。。。 自分のComponentが機能優先でごちゃついているので、参考にさせていただきます！ 各ディレクトリにindexでexportしているのも良いと思います！

改善の余地は、色々あると思いますが…スッキリまとめられた部分もちょこちょこあるかと、自負しています😤ｗ

> ### 僭越ながら改善点です。
> * Bargurを使ってMobileNavを作ると更に良くなると思います！
> * Componentをパーツごとに分けると、ぱっと見たときに見やすくなるかもしれません。。。

- モバイル対応は、永遠の課題なので、ボチボチ対応してみたいと思います！😆

- パーツごとですか〜もし可能なら、どこの何を切り出すと良さそうとか教えて頂けますか？
一応実際、見やすく出来ていない部分は多々あるかと思うので、リファクタリングで改善させて頂きます🙇

> ### さいごに
> 初めてのレビューなのでちゃんとできているか不明ですが、 宜しくお願いいたします。

大丈夫です！助かります😄

今回のは、いわゆるプルリク→レビューの流れじゃないので、ある意味自由に書けるかと思ってますｗ

レビューも多分、繰り返しやっていくことで良くなると思うので、バンバンやって力を身に着けたいですよね〜😊
