### ISSUE TITLE
レビュー（かみかみ）

### ISSUE THREAD

**Issue by Hobiron03** [tatsuya19881021/qin-portfolio#6]
Goodポイント
・全てのコンポーネントをindex.ts エクスポートしているのはとても良いですね！
・コンポーネントの一つ一つがコンパクトにまとまっていてとても見やすいです！見習わせていただきます🙏
・Home で表示するブログリンクの数とかもしっかり制御されていて、今後を見据えてしっかりと開発されている印象でした！

Mottoポイント
・ご自身の Issue でも言及されていましたが、footer の固定が出来ているとさらに良いと思います！色々やり方はあるみたいですが、flexbox を使った方法が一番やりやすかったです。

人にコードを見ると勉強になりますね。ちょっと上から目線だったりしたらすみません🙇‍♂️

**Comment by tatsuya19881021** [comment]
@Hobiron03 

レビューありがとうございます！

> Goodポイント ・全てのコンポーネントをindex.ts エクスポートしているのはとても良いですね！ ・コンポーネントの一つ一つがコンパクトにまとまっていてとても見やすいです！見習わせていただきます🙏 ・Home で表示するブログリンクの数とかもしっかり制御されていて、今後を見据えてしっかりと開発されている印象でした！

細かいところまで見て頂いて助かります^^
実データより、仮データで実装するのは割と好きかもしれませんｗ

> 
> Mottoポイント ・ご自身の Issue でも言及されていましたが、footer の固定が出来ているとさらに良いと思います！色々やり方はあるみたいですが、flexbox を使った方法が一番やりやすかったです。
> 
> 人にコードを見ると勉強になりますね。ちょっと上から目線だったりしたらすみません🙇‍♂️

なるほど〜。ありがとうございます。
リファクタリングが進んでいないので、ちゃんと進めていこうと思います😆
footerのflexbox、勉強してみます💪

全然、色んな意見を頂きたいので、嬉しいです。
コード見て勉強して、自分にも取り入れて、キレイなものを書けるようにしたいですよね〜
